apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demoApp
  namespace: argocd
spec:
  destination:
    namespace: demo
    server: https://kubernetes.default.svc
  project: default
  source:
    path: demo/
    repoURL: https://github.com/akhan23wgu/argocd-helloworld
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
