apiVersion: v1
kind: ConfigMap
metadata:
        name: index-html-configmap
        namespace: demo
        data:
                index.html: |
                          <html>
                          <h1>Welcome</h1>
                          </br>
                          <h1> another project completed </h1>
                          </html>
                    