apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apache
  namespace: demo
spec:
  project: default
  destination:
    name: ''
    namespace: demo
    server: 'https://kubernetes.default.svc'
  source:
    path: 'apache'
    repoURL: 'registry-1.docker.io/bitnamicharts'
    targetRevision: 11.0.0
    chart: apache
    helm:
      values: |-
        parameters:
         - name: service.type
           value: "NodePort"
         - name: htdocsConfigMap
           value: "index-html-configmap"
         - name: service.NodePorts.http
           value: "30129"
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
