apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  project: default
  destination:
    name: ''
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: 'nginx'
    repoURL: 'registry-1.docker.io/bitnamicharts'
    targetRevision: "15.14.0"
    chart: nginx
    helm:
      values: |-
        service:
          type: "NodePort"
        staticSiteConfigmap: "index-html-configmap"
        serverBlock: |-
          server {
            listen 8080;
            root /app/;
            index index.html index.htm;
            location /demoVol/ {
              alias /demoVol/;
              index __i;
              autoindex on;
              autoindex_format json;
              disable_symlinks off;
            }
            location / {
              root /app/;
            }
          }
        extraDeploy:
          - |
            apiVersion: v1
            kind: PersistentVolumeClaim
            metadata:
              name: demoVol
            spec:
              accessModes:
              - ReadWriteOnce
              resources:
                requests:
                  storage: 4Gi
        extraVolumes:
          - name: demoVol
            persistentVolumeClaim:
              claimName: demoVol
        extraVolumeMounts:
          - mountPath: /demoVol
            name: demoVol
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
